[phases.setup]
nixPkgs = ['python311']

[phases.install]
cmds = ['pip install uv', 'uv sync']

[phases.build]
cmds = ['echo "Skipping collectstatic during build - will run in release phase"']

[start]
cmd = 'uv run gunicorn bookclerk_project.wsgi --log-file -'