# Generated by Django 5.2.5 on 2025-08-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrecommendation',
            name='amazon_url',
            field=models.URLField(blank=True, help_text='Amazon affiliate link', null=True),
        ),
    ]
