# Generated by Django 5.2.5 on 2025-08-18 17:20

import uuid
from django.db import migrations, models
from django.db.models import deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_bookrecommendation_amazon_url'),
    ]

    operations = [
        # Remove the old table and recreate with correct schema
        migrations.RunSQL(
            "DROP TABLE IF EXISTS recommendations_recommendationrequest;",
            reverse_sql="SELECT 1;"  # Irreversible operation
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS recommendations_bookrecommendation;",
            reverse_sql="SELECT 1;"  # Irreversible operation
        ),
        # Recreate the tables with correct schema
        migrations.CreateModel(
            name='RecommendationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_preferences', models.TextField(help_text="User's book preferences and interests")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('reason', models.TextField(help_text='Why this book was recommended')),
                ('amazon_url', models.URLField(blank=True, help_text='Amazon affiliate link', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='recommendations', to='recommendations.recommendationrequest')),
            ],
        ),
    ]
